/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as GuidelinesRouteImport } from './routes/guidelines'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GamesIndexRouteImport } from './routes/games/index'
import { Route as DraftsIndexRouteImport } from './routes/drafts/index'
import { Route as ReviewsNewRouteImport } from './routes/reviews/new'
import { Route as ReviewsIdRouteImport } from './routes/reviews/$id'
import { Route as QuestlogUsernameRouteImport } from './routes/questlog/$username'
import { Route as ProfileUsernameRouteImport } from './routes/profile/$username'
import { Route as PostsIdRouteImport } from './routes/posts/$id'
import { Route as GamesSlugRouteImport } from './routes/games/$slug'
import { Route as ArticlesNewRouteImport } from './routes/articles/new'
import { Route as ArticlesIdRouteImport } from './routes/articles/$id'
import { Route as ApiUploadthingRouteImport } from './routes/api/uploadthing'
import { Route as ReviewsEditIdRouteImport } from './routes/reviews/edit.$id'
import { Route as ArticlesEditIdRouteImport } from './routes/articles/edit.$id'
import { Route as ApiCronCleanupRouteImport } from './routes/api/cron/cleanup'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidelinesRoute = GuidelinesRouteImport.update({
  id: '/guidelines',
  path: '/guidelines',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIndexRoute = GamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => rootRouteImport,
} as any)
const DraftsIndexRoute = DraftsIndexRouteImport.update({
  id: '/drafts/',
  path: '/drafts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsNewRoute = ReviewsNewRouteImport.update({
  id: '/reviews/new',
  path: '/reviews/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsIdRoute = ReviewsIdRouteImport.update({
  id: '/reviews/$id',
  path: '/reviews/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestlogUsernameRoute = QuestlogUsernameRouteImport.update({
  id: '/questlog/$username',
  path: '/questlog/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUsernameRoute = ProfileUsernameRouteImport.update({
  id: '/profile/$username',
  path: '/profile/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIdRoute = PostsIdRouteImport.update({
  id: '/posts/$id',
  path: '/posts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesSlugRoute = GamesSlugRouteImport.update({
  id: '/games/$slug',
  path: '/games/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesNewRoute = ArticlesNewRouteImport.update({
  id: '/articles/new',
  path: '/articles/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIdRoute = ArticlesIdRouteImport.update({
  id: '/articles/$id',
  path: '/articles/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadthingRoute = ApiUploadthingRouteImport.update({
  id: '/api/uploadthing',
  path: '/api/uploadthing',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsEditIdRoute = ReviewsEditIdRouteImport.update({
  id: '/reviews/edit/$id',
  path: '/reviews/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesEditIdRoute = ArticlesEditIdRouteImport.update({
  id: '/articles/edit/$id',
  path: '/articles/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronCleanupRoute = ApiCronCleanupRouteImport.update({
  id: '/api/cron/cleanup',
  path: '/api/cron/cleanup',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/guidelines': typeof GuidelinesRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/articles/$id': typeof ArticlesIdRoute
  '/articles/new': typeof ArticlesNewRoute
  '/games/$slug': typeof GamesSlugRoute
  '/posts/$id': typeof PostsIdRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/questlog/$username': typeof QuestlogUsernameRoute
  '/reviews/$id': typeof ReviewsIdRoute
  '/reviews/new': typeof ReviewsNewRoute
  '/drafts/': typeof DraftsIndexRoute
  '/games/': typeof GamesIndexRoute
  '/api/cron/cleanup': typeof ApiCronCleanupRoute
  '/articles/edit/$id': typeof ArticlesEditIdRoute
  '/reviews/edit/$id': typeof ReviewsEditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/guidelines': typeof GuidelinesRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/articles/$id': typeof ArticlesIdRoute
  '/articles/new': typeof ArticlesNewRoute
  '/games/$slug': typeof GamesSlugRoute
  '/posts/$id': typeof PostsIdRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/questlog/$username': typeof QuestlogUsernameRoute
  '/reviews/$id': typeof ReviewsIdRoute
  '/reviews/new': typeof ReviewsNewRoute
  '/drafts': typeof DraftsIndexRoute
  '/games': typeof GamesIndexRoute
  '/api/cron/cleanup': typeof ApiCronCleanupRoute
  '/articles/edit/$id': typeof ArticlesEditIdRoute
  '/reviews/edit/$id': typeof ReviewsEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/guidelines': typeof GuidelinesRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/articles/$id': typeof ArticlesIdRoute
  '/articles/new': typeof ArticlesNewRoute
  '/games/$slug': typeof GamesSlugRoute
  '/posts/$id': typeof PostsIdRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/questlog/$username': typeof QuestlogUsernameRoute
  '/reviews/$id': typeof ReviewsIdRoute
  '/reviews/new': typeof ReviewsNewRoute
  '/drafts/': typeof DraftsIndexRoute
  '/games/': typeof GamesIndexRoute
  '/api/cron/cleanup': typeof ApiCronCleanupRoute
  '/articles/edit/$id': typeof ArticlesEditIdRoute
  '/reviews/edit/$id': typeof ReviewsEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/guidelines'
    | '/sign-in'
    | '/sign-up'
    | '/api/uploadthing'
    | '/articles/$id'
    | '/articles/new'
    | '/games/$slug'
    | '/posts/$id'
    | '/profile/$username'
    | '/questlog/$username'
    | '/reviews/$id'
    | '/reviews/new'
    | '/drafts/'
    | '/games/'
    | '/api/cron/cleanup'
    | '/articles/edit/$id'
    | '/reviews/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/guidelines'
    | '/sign-in'
    | '/sign-up'
    | '/api/uploadthing'
    | '/articles/$id'
    | '/articles/new'
    | '/games/$slug'
    | '/posts/$id'
    | '/profile/$username'
    | '/questlog/$username'
    | '/reviews/$id'
    | '/reviews/new'
    | '/drafts'
    | '/games'
    | '/api/cron/cleanup'
    | '/articles/edit/$id'
    | '/reviews/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/guidelines'
    | '/sign-in'
    | '/sign-up'
    | '/api/uploadthing'
    | '/articles/$id'
    | '/articles/new'
    | '/games/$slug'
    | '/posts/$id'
    | '/profile/$username'
    | '/questlog/$username'
    | '/reviews/$id'
    | '/reviews/new'
    | '/drafts/'
    | '/games/'
    | '/api/cron/cleanup'
    | '/articles/edit/$id'
    | '/reviews/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GuidelinesRoute: typeof GuidelinesRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  ApiUploadthingRoute: typeof ApiUploadthingRoute
  ArticlesIdRoute: typeof ArticlesIdRoute
  ArticlesNewRoute: typeof ArticlesNewRoute
  GamesSlugRoute: typeof GamesSlugRoute
  PostsIdRoute: typeof PostsIdRoute
  ProfileUsernameRoute: typeof ProfileUsernameRoute
  QuestlogUsernameRoute: typeof QuestlogUsernameRoute
  ReviewsIdRoute: typeof ReviewsIdRoute
  ReviewsNewRoute: typeof ReviewsNewRoute
  DraftsIndexRoute: typeof DraftsIndexRoute
  GamesIndexRoute: typeof GamesIndexRoute
  ApiCronCleanupRoute: typeof ApiCronCleanupRoute
  ArticlesEditIdRoute: typeof ArticlesEditIdRoute
  ReviewsEditIdRoute: typeof ReviewsEditIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guidelines': {
      id: '/guidelines'
      path: '/guidelines'
      fullPath: '/guidelines'
      preLoaderRoute: typeof GuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/': {
      id: '/games/'
      path: '/games'
      fullPath: '/games/'
      preLoaderRoute: typeof GamesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drafts/': {
      id: '/drafts/'
      path: '/drafts'
      fullPath: '/drafts/'
      preLoaderRoute: typeof DraftsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews/new': {
      id: '/reviews/new'
      path: '/reviews/new'
      fullPath: '/reviews/new'
      preLoaderRoute: typeof ReviewsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews/$id': {
      id: '/reviews/$id'
      path: '/reviews/$id'
      fullPath: '/reviews/$id'
      preLoaderRoute: typeof ReviewsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questlog/$username': {
      id: '/questlog/$username'
      path: '/questlog/$username'
      fullPath: '/questlog/$username'
      preLoaderRoute: typeof QuestlogUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$username': {
      id: '/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof ProfileUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$id': {
      id: '/posts/$id'
      path: '/posts/$id'
      fullPath: '/posts/$id'
      preLoaderRoute: typeof PostsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$slug': {
      id: '/games/$slug'
      path: '/games/$slug'
      fullPath: '/games/$slug'
      preLoaderRoute: typeof GamesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/new': {
      id: '/articles/new'
      path: '/articles/new'
      fullPath: '/articles/new'
      preLoaderRoute: typeof ArticlesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$id': {
      id: '/articles/$id'
      path: '/articles/$id'
      fullPath: '/articles/$id'
      preLoaderRoute: typeof ArticlesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploadthing': {
      id: '/api/uploadthing'
      path: '/api/uploadthing'
      fullPath: '/api/uploadthing'
      preLoaderRoute: typeof ApiUploadthingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews/edit/$id': {
      id: '/reviews/edit/$id'
      path: '/reviews/edit/$id'
      fullPath: '/reviews/edit/$id'
      preLoaderRoute: typeof ReviewsEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/edit/$id': {
      id: '/articles/edit/$id'
      path: '/articles/edit/$id'
      fullPath: '/articles/edit/$id'
      preLoaderRoute: typeof ArticlesEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/cleanup': {
      id: '/api/cron/cleanup'
      path: '/api/cron/cleanup'
      fullPath: '/api/cron/cleanup'
      preLoaderRoute: typeof ApiCronCleanupRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GuidelinesRoute: GuidelinesRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  ApiUploadthingRoute: ApiUploadthingRoute,
  ArticlesIdRoute: ArticlesIdRoute,
  ArticlesNewRoute: ArticlesNewRoute,
  GamesSlugRoute: GamesSlugRoute,
  PostsIdRoute: PostsIdRoute,
  ProfileUsernameRoute: ProfileUsernameRoute,
  QuestlogUsernameRoute: QuestlogUsernameRoute,
  ReviewsIdRoute: ReviewsIdRoute,
  ReviewsNewRoute: ReviewsNewRoute,
  DraftsIndexRoute: DraftsIndexRoute,
  GamesIndexRoute: GamesIndexRoute,
  ApiCronCleanupRoute: ApiCronCleanupRoute,
  ArticlesEditIdRoute: ArticlesEditIdRoute,
  ReviewsEditIdRoute: ReviewsEditIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
