/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GamesIndexRouteImport } from './routes/games/index'
import { Route as ReviewsNewRouteImport } from './routes/reviews/new'
import { Route as ReviewsIdRouteImport } from './routes/reviews/$id'
import { Route as ProfileUsernameRouteImport } from './routes/profile/$username'
import { Route as PostsIdRouteImport } from './routes/posts/$id'
import { Route as GamesSlugRouteImport } from './routes/games/$slug'
import { Route as ArticlesNewRouteImport } from './routes/articles/new'
import { Route as ArticlesIdRouteImport } from './routes/articles/$id'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIndexRoute = GamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsNewRoute = ReviewsNewRouteImport.update({
  id: '/reviews/new',
  path: '/reviews/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsIdRoute = ReviewsIdRouteImport.update({
  id: '/reviews/$id',
  path: '/reviews/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUsernameRoute = ProfileUsernameRouteImport.update({
  id: '/profile/$username',
  path: '/profile/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIdRoute = PostsIdRouteImport.update({
  id: '/posts/$id',
  path: '/posts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesSlugRoute = GamesSlugRouteImport.update({
  id: '/games/$slug',
  path: '/games/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesNewRoute = ArticlesNewRouteImport.update({
  id: '/articles/new',
  path: '/articles/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIdRoute = ArticlesIdRouteImport.update({
  id: '/articles/$id',
  path: '/articles/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/articles/$id': typeof ArticlesIdRoute
  '/articles/new': typeof ArticlesNewRoute
  '/games/$slug': typeof GamesSlugRoute
  '/posts/$id': typeof PostsIdRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/reviews/$id': typeof ReviewsIdRoute
  '/reviews/new': typeof ReviewsNewRoute
  '/games/': typeof GamesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/articles/$id': typeof ArticlesIdRoute
  '/articles/new': typeof ArticlesNewRoute
  '/games/$slug': typeof GamesSlugRoute
  '/posts/$id': typeof PostsIdRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/reviews/$id': typeof ReviewsIdRoute
  '/reviews/new': typeof ReviewsNewRoute
  '/games': typeof GamesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/articles/$id': typeof ArticlesIdRoute
  '/articles/new': typeof ArticlesNewRoute
  '/games/$slug': typeof GamesSlugRoute
  '/posts/$id': typeof PostsIdRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/reviews/$id': typeof ReviewsIdRoute
  '/reviews/new': typeof ReviewsNewRoute
  '/games/': typeof GamesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/articles/$id'
    | '/articles/new'
    | '/games/$slug'
    | '/posts/$id'
    | '/profile/$username'
    | '/reviews/$id'
    | '/reviews/new'
    | '/games/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/articles/$id'
    | '/articles/new'
    | '/games/$slug'
    | '/posts/$id'
    | '/profile/$username'
    | '/reviews/$id'
    | '/reviews/new'
    | '/games'
  id:
    | '__root__'
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/articles/$id'
    | '/articles/new'
    | '/games/$slug'
    | '/posts/$id'
    | '/profile/$username'
    | '/reviews/$id'
    | '/reviews/new'
    | '/games/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  ArticlesIdRoute: typeof ArticlesIdRoute
  ArticlesNewRoute: typeof ArticlesNewRoute
  GamesSlugRoute: typeof GamesSlugRoute
  PostsIdRoute: typeof PostsIdRoute
  ProfileUsernameRoute: typeof ProfileUsernameRoute
  ReviewsIdRoute: typeof ReviewsIdRoute
  ReviewsNewRoute: typeof ReviewsNewRoute
  GamesIndexRoute: typeof GamesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/': {
      id: '/games/'
      path: '/games'
      fullPath: '/games/'
      preLoaderRoute: typeof GamesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews/new': {
      id: '/reviews/new'
      path: '/reviews/new'
      fullPath: '/reviews/new'
      preLoaderRoute: typeof ReviewsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews/$id': {
      id: '/reviews/$id'
      path: '/reviews/$id'
      fullPath: '/reviews/$id'
      preLoaderRoute: typeof ReviewsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$username': {
      id: '/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof ProfileUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$id': {
      id: '/posts/$id'
      path: '/posts/$id'
      fullPath: '/posts/$id'
      preLoaderRoute: typeof PostsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$slug': {
      id: '/games/$slug'
      path: '/games/$slug'
      fullPath: '/games/$slug'
      preLoaderRoute: typeof GamesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/new': {
      id: '/articles/new'
      path: '/articles/new'
      fullPath: '/articles/new'
      preLoaderRoute: typeof ArticlesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$id': {
      id: '/articles/$id'
      path: '/articles/$id'
      fullPath: '/articles/$id'
      preLoaderRoute: typeof ArticlesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  ArticlesIdRoute: ArticlesIdRoute,
  ArticlesNewRoute: ArticlesNewRoute,
  GamesSlugRoute: GamesSlugRoute,
  PostsIdRoute: PostsIdRoute,
  ProfileUsernameRoute: ProfileUsernameRoute,
  ReviewsIdRoute: ReviewsIdRoute,
  ReviewsNewRoute: ReviewsNewRoute,
  GamesIndexRoute: GamesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
